services:
  backend:
    build: ./backend
    container_name: buscador-marca-backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_TRACING_V2=true
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - MAX_FILE_SIZE=0
      - MAX_CONCURRENT_PAGES=8
      - PROCESSING_TIMEOUT=0
      - BATCH_SIZE=8
      - MAX_CONCURRENT_BATCHES=3
      - PDF_DPI=300
      - MAX_IMAGE_SIZE=20000
      - IMAGE_QUALITY=95
      - THREAD_POOL_SIZE=8
      - CONNECTION_POOL_SIZE=10
      - REQUEST_TIMEOUT=0
      - USE_GPU=false
      - OCR_LANGUAGES=es,en
      - OCR_CONFIDENCE_THRESHOLD=0.3
      - OCR_MAX_RETRIES=3
      - OCR_RETRY_DELAY=1.0
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - buscador-marca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    container_name: buscador-marca-frontend
    ports:
      - "0.0.0.0:80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - buscador-marca-network
    restart: unless-stopped

networks:
  buscador-marca-network:
    driver: bridge

volumes:
  uploads:
